apiVersion: v1
kind: Service
metadata:
  name: frontend-challenge-service
  namespace: argocd
spec:
  selector:
    app: frontend-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
