apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'mongo'
        static_configs:
          - targets:
              - mongo-replica-set-0.mongo:27017
              - mongo-replica-set-1.mongo:27017
              - mongo-replica-set-2.mongo:27017
